name: cords-geoprocessing

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.3
  - jupyter
  - python-wget
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - rasterio
  - shapely
  - xdem
  - rasterstats
