name: cords-geoprocessing

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12.3
  - jupyter=1.0.0
  - python-wget
  - geopandas=0.14.2
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pandas=2.2.1
  - rasterio=1.3.9
  - shapely=2.0.4
  - xdem=0.0.18
  - rasterstats=0.14.0
